In [16]:
import numpy as np
import test_vars.vars as vs

In [17]:
vs.list1d

array([1, 2, 3])

In [11]:
# Concatenating a 3d array along dimension 0 returns the correct resultj
t1 = np.array(
    [[[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]],
    [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]]
)

c0 = np.concatenate([t1, (t1[[0]] + 1)], axis=0)
print(c0.shape)
print(c0)

(3, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]]


In [10]:
# Concatenating a 3d array along dimension 1 returns the correct result
c1 = np.concatenate([t1, t1[:, [0], :] + 1], axis=1)
print(c1.shape)
print(c1)

(2, 4, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 2  3  4  5]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [14 15 16 17]]]


In [12]:
# Concatenating a 3d array along dimension 2 returns the correct result
c2 = np.concatenate([t1, t1[:, :, [0]] + 1], axis=2)
print(c2.shape)
print(c2)

(2, 3, 5)
[[[ 1  2  3  4  2]
  [ 5  6  7  8  6]
  [ 9 10 11 12 10]]

 [[13 14 15 16 14]
  [17 18 19 20 18]
  [21 22 23 24 22]]]
