In [1]:
import numpy as np
import test_vars.vars as vs

In [2]:
vs.dbl3d

array([[[0.1, 0.2, 0.3, 0.4, 0.5],
        [1.1, 1.2, 1.3, 1.4, 1.5],
        [2.1, 2.2, 2.3, 2.4, 2.5]],

       [[3.1, 3.2, 3.3, 3.4, 3.5],
        [4.1, 4.2, 4.3, 4.4, 4.5],
        [5.1, 5.2, 5.3, 5.4, 5.5]]])

In [4]:
# Concatenating a 3d array along dimension 0 returns the correct resultj
t1 = np.array(
    [[[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]],
    [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]]
)

c0 = np.concatenate([t1, (t1[[0]] + 1)], axis=0)
print(c0.shape)
print(c0)

(3, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]]


In [18]:
# Concatenating a 3d array along dimension 1 returns the correct result
c1 = np.concatenate([t1, t1[:, [0], :] + 1], axis=1)
print(c1.shape)
print(c1)

(2, 4, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 2  3  4  5]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [14 15 16 17]]]


In [48]:
# Concatenate cannot be replicated with any combination of flatten and reshape. F and F
# def sconc(t1, shape):
    
fl = np.concatenate([t1.flatten(order='A'), (t1[:, [0], :] + 1).flatten(order='A')], axis = 0)
fl.reshape([2, 4, 4], order='A')

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [ 2,  3,  4,  5],
        [14, 15, 16, 17]]])

In [29]:
# Attempting to reconstruct using other reshape methodologies


In [30]:
# reshape is working the same way in both numpy and sport
fl.reshape([2, 4, 4])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [ 2,  3,  4,  5],
        [14, 15, 16, 17]]])

In [6]:
# Concatenating a 3d array along dimension 2 returns the correct result
c2 = np.concatenate([t1, t1[:, :, [0]] + 1], axis=2)
print(c2.shape)
print(c2)

(2, 3, 5)
[[[ 1  2  3  4  2]
  [ 5  6  7  8  6]
  [ 9 10 11 12 10]]

 [[13 14 15 16 14]
  [17 18 19 20 18]
  [21 22 23 24 22]]]


In [49]:
test1 = np.array(
    [[[1.1, 1.2, 1.3],
      [1.01, 1.02, 1.03]],
     [[2.1, 2.2, 2.3],
      [2.01, 2.02, 2.03]]]
)
test1

array([[[1.1 , 1.2 , 1.3 ],
        [1.01, 1.02, 1.03]],

       [[2.1 , 2.2 , 2.3 ],
        [2.01, 2.02, 2.03]]])

In [56]:
test2 = test1 + 2.
test2 = test2[:, [0], :]
test2

array([[[3.1, 3.2, 3.3]],

       [[4.1, 4.2, 4.3]]])

In [58]:
test1.flatten()

array([1.1 , 1.2 , 1.3 , 1.01, 1.02, 1.03, 2.1 , 2.2 , 2.3 , 2.01, 2.02,
       2.03])

In [57]:
np.concatenate([test1, test2], axis=1)

array([[[1.1 , 1.2 , 1.3 ],
        [1.01, 1.02, 1.03],
        [3.1 , 3.2 , 3.3 ]],

       [[2.1 , 2.2 , 2.3 ],
        [2.01, 2.02, 2.03],
        [4.1 , 4.2 , 4.3 ]]])

In [59]:
np.concatenate([test1, test2], axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
# If we flatten then the t2 values will be at the end of the list, naturally.
# This would mean that these six cells end up as the final two elems of dim0: 1
# Because we are intending to add
# BThis would be avoided if we 