In [1]:
import numpy as np
from test_vars.vars import *

In [2]:
dbl2d

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [3]:
# dbl2d.flatten returns the correct List[T]
dbl2d.flatten()

array([0.1, 0.2, 0.3, 0.4, 0.5, 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2, 2.3,
       2.4, 2.5])

In [9]:
# dbl3d.flatten returns the correct List[T]
dbl3d.flatten()

array([0.1, 0.2, 0.3, 0.4, 0.5, 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2, 2.3,
       2.4, 2.5, 3.1, 3.2, 3.3, 3.4, 3.5, 4.1, 4.2, 4.3, 4.4, 4.5, 5.1,
       5.2, 5.3, 5.4, 5.5])