In [1]:
import numpy as np
from test_vars.vars import *

In [2]:
dbl2d

array([[0.  , 0.01, 0.02, 0.03, 0.04],
       [0.1 , 0.11, 0.12, 0.13, 0.14],
       [0.2 , 0.21, 0.22, 0.23, 0.24]])

In [3]:
# dbl2d.flatten returns the correct List[T]
dbl2d.flatten()

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.1 , 0.11, 0.12, 0.13, 0.14, 0.2 ,
       0.21, 0.22, 0.23, 0.24])

In [4]:
# dbl3d.flatten returns the correct List[T]
dbl3d.flatten()

array([0.   , 0.001, 0.002, 0.003, 0.004, 0.01 , 0.011, 0.012, 0.013,
       0.014, 0.02 , 0.021, 0.022, 0.023, 0.024, 0.1  , 0.101, 0.102,
       0.103, 0.104, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.12 , 0.121,
       0.122, 0.123, 0.124])