In [ ]:
import numpy as np
from test_vars.vars import *

In [3]:
dbl2d

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [6]:
mask2d = np.array(
    [[False, True, True, True, True],
     [True, False, True, True, True],
     [True, True, False, True, True]]
)


In [7]:
dbl2d[mask2d]

array([0.2, 0.3, 0.4, 0.5, 1.1, 1.3, 1.4, 1.5, 2.1, 2.2, 2.4, 2.5])

In [11]:
dbl2d[1:4, 0:1]

array([[1.1],
       [2.1]])

In [1]:
dbl2d.expand_dims(0)

NameError: name 'dbl2d' is not defined