In [19]:
import numpy as np
from test_vars.vars import *
np.set_printoptions(suppress=True)

In [20]:
dbl2d.shape

(3, 5)

In [21]:
dbl2d

array([[0.  , 0.01, 0.02, 0.03, 0.04],
       [0.1 , 0.11, 0.12, 0.13, 0.14],
       [0.2 , 0.21, 0.22, 0.23, 0.24]])

In [22]:
dbl2d.T

array([[0.  , 0.1 , 0.2 ],
       [0.01, 0.11, 0.21],
       [0.02, 0.12, 0.22],
       [0.03, 0.13, 0.23],
       [0.04, 0.14, 0.24]])

In [23]:
dbl3d.shape

(2, 3, 5)

In [24]:
dbl3d.T.shape

(5, 3, 2)

In [27]:
dbl4d.T

array([[[[0.    , 0.1   ],
         [0.01  , 0.11  ]],

        [[0.001 , 0.101 ],
         [0.011 , 0.111 ]],

        [[0.002 , 0.102 ],
         [0.012 , 0.112 ]]],


       [[[0.0001, 0.1001],
         [0.0101, 0.1101]],

        [[0.0011, 0.1011],
         [0.0111, 0.1111]],

        [[0.0021, 0.1021],
         [0.0121, 0.1121]]],


       [[[0.0002, 0.1002],
         [0.0102, 0.1102]],

        [[0.0012, 0.1012],
         [0.0112, 0.1112]],

        [[0.0022, 0.1022],
         [0.0122, 0.1122]]],


       [[[0.0003, 0.1003],
         [0.0103, 0.1103]],

        [[0.0013, 0.1013],
         [0.0113, 0.1113]],

        [[0.0023, 0.1023],
         [0.0123, 0.1123]]],


       [[[0.0004, 0.1004],
         [0.0104, 0.1104]],

        [[0.0014, 0.1014],
         [0.0114, 0.1114]],

        [[0.0024, 0.1024],
         [0.0124, 0.1124]]]])

In [26]:
dbl4d.transpose(0,1,3,2)

array([[[[0.    , 0.001 , 0.002 ],
         [0.0001, 0.0011, 0.0021],
         [0.0002, 0.0012, 0.0022],
         [0.0003, 0.0013, 0.0023],
         [0.0004, 0.0014, 0.0024]],

        [[0.01  , 0.011 , 0.012 ],
         [0.0101, 0.0111, 0.0121],
         [0.0102, 0.0112, 0.0122],
         [0.0103, 0.0113, 0.0123],
         [0.0104, 0.0114, 0.0124]]],


       [[[0.1   , 0.101 , 0.102 ],
         [0.1001, 0.1011, 0.1021],
         [0.1002, 0.1012, 0.1022],
         [0.1003, 0.1013, 0.1023],
         [0.1004, 0.1014, 0.1024]],

        [[0.11  , 0.111 , 0.112 ],
         [0.1101, 0.1111, 0.1121],
         [0.1102, 0.1112, 0.1122],
         [0.1103, 0.1113, 0.1123],
         [0.1104, 0.1114, 0.1124]]]])

In [9]:
dbl4d.transpose(
    1,0,2,3).transpose(
    0,2,1,3).transpose(
    0,1,3,2).transpose(
    1,0,2,3).transpose(
    0,2,1,3).transpose(
    1,0,2,3) == dbl4d.T

array([[[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])

In [10]:
dbl4d.T

array([[[[0.000e+00, 1.000e-01],
         [1.000e-02, 1.100e-01]],

        [[1.000e-03, 1.010e-01],
         [1.100e-02, 1.110e-01]],

        [[2.000e-03, 1.020e-01],
         [1.200e-02, 1.120e-01]]],


       [[[1.000e-04, 1.001e-01],
         [1.010e-02, 1.101e-01]],

        [[1.100e-03, 1.011e-01],
         [1.110e-02, 1.111e-01]],

        [[2.100e-03, 1.021e-01],
         [1.210e-02, 1.121e-01]]],


       [[[2.000e-04, 1.002e-01],
         [1.020e-02, 1.102e-01]],

        [[1.200e-03, 1.012e-01],
         [1.120e-02, 1.112e-01]],

        [[2.200e-03, 1.022e-01],
         [1.220e-02, 1.122e-01]]],


       [[[3.000e-04, 1.003e-01],
         [1.030e-02, 1.103e-01]],

        [[1.300e-03, 1.013e-01],
         [1.130e-02, 1.113e-01]],

        [[2.300e-03, 1.023e-01],
         [1.230e-02, 1.123e-01]]],


       [[[4.000e-04, 1.004e-01],
         [1.040e-02, 1.104e-01]],

        [[1.400e-03, 1.014e-01],
         [1.140e-02, 1.114e-01]],

        [[2.400e-03, 1.024e-01],
       

In [11]:
dbl3d

array([[[0.   , 0.001, 0.002, 0.003, 0.004],
        [0.01 , 0.011, 0.012, 0.013, 0.014],
        [0.02 , 0.021, 0.022, 0.023, 0.024]],

       [[0.1  , 0.101, 0.102, 0.103, 0.104],
        [0.11 , 0.111, 0.112, 0.113, 0.114],
        [0.12 , 0.121, 0.122, 0.123, 0.124]]])

In [12]:
dbl3d.transpose(0,2,1).transpose(1, 0,2)

array([[[0.   , 0.01 , 0.02 ],
        [0.1  , 0.11 , 0.12 ]],

       [[0.001, 0.011, 0.021],
        [0.101, 0.111, 0.121]],

       [[0.002, 0.012, 0.022],
        [0.102, 0.112, 0.122]],

       [[0.003, 0.013, 0.023],
        [0.103, 0.113, 0.123]],

       [[0.004, 0.014, 0.024],
        [0.104, 0.114, 0.124]]])

In [13]:
t1 = np.random.rand(2,3,4,5)
t1.T.shape

(5, 4, 3, 2)

In [14]:
dbl3d.T

array([[[0.   , 0.1  ],
        [0.01 , 0.11 ],
        [0.02 , 0.12 ]],

       [[0.001, 0.101],
        [0.011, 0.111],
        [0.021, 0.121]],

       [[0.002, 0.102],
        [0.012, 0.112],
        [0.022, 0.122]],

       [[0.003, 0.103],
        [0.013, 0.113],
        [0.023, 0.123]],

       [[0.004, 0.104],
        [0.014, 0.114],
        [0.024, 0.124]]])

In [15]:
dbl3d.transpose(0,2,1)

array([[[0.   , 0.01 , 0.02 ],
        [0.001, 0.011, 0.021],
        [0.002, 0.012, 0.022],
        [0.003, 0.013, 0.023],
        [0.004, 0.014, 0.024]],

       [[0.1  , 0.11 , 0.12 ],
        [0.101, 0.111, 0.121],
        [0.102, 0.112, 0.122],
        [0.103, 0.113, 0.123],
        [0.104, 0.114, 0.124]]])

In [16]:
test3d = np.array(
    [[[1 , 2 , 3 , 4 ],
      [5 , 6 , 7 , 8 ],
      [9 , 10, 11, 12]],
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]]
)
test3d.shape

(2, 3, 4)

In [17]:
test3d.transpose(0, 2, 1)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [18]:
t1 = np.array(
    [[[[1 , 2],
       [3 , 4],
       [5 , 6]],
      [[7 , 8],
       [9 ,10],
       [11,12]]],
     [[[13,14],
       [15,16],
       [17,18]],
      [[19,20],
       [21,22],
       [22,23]]]]
)
t1.transpose(0,1,3,2)

array([[[[ 1,  3,  5],
         [ 2,  4,  6]],

        [[ 7,  9, 11],
         [ 8, 10, 12]]],


       [[[13, 15, 17],
         [14, 16, 18]],

        [[19, 21, 22],
         [20, 22, 23]]]])