In [2]:
import numpy as np
from test_vars.vars import *

In [11]:
dbl2d.shape

(3, 5)

In [14]:
dbl2d

array([[0.  , 0.01, 0.02, 0.03, 0.04],
       [0.1 , 0.11, 0.12, 0.13, 0.14],
       [0.2 , 0.21, 0.22, 0.23, 0.24]])

In [13]:
dbl2d.T

array([[0.  , 0.1 , 0.2 ],
       [0.01, 0.11, 0.21],
       [0.02, 0.12, 0.22],
       [0.03, 0.13, 0.23],
       [0.04, 0.14, 0.24]])

In [4]:
dbl3d.shape

(2, 3, 5)

In [3]:
dbl3d.T.shape

(5, 3, 2)

In [9]:
dbl3d.T

array([[[0.   , 0.1  ],
        [0.01 , 0.11 ],
        [0.02 , 0.12 ]],

       [[0.001, 0.101],
        [0.011, 0.111],
        [0.021, 0.121]],

       [[0.002, 0.102],
        [0.012, 0.112],
        [0.022, 0.122]],

       [[0.003, 0.103],
        [0.013, 0.113],
        [0.023, 0.123]],

       [[0.004, 0.104],
        [0.014, 0.114],
        [0.024, 0.124]]])

In [8]:
dbl3d.transpose(0,2,1).shape

(2, 5, 3)

In [10]:
dbl3d.transpose(0,2,1)

array([[[0.   , 0.01 , 0.02 ],
        [0.001, 0.011, 0.021],
        [0.002, 0.012, 0.022],
        [0.003, 0.013, 0.023],
        [0.004, 0.014, 0.024]],

       [[0.1  , 0.11 , 0.12 ],
        [0.101, 0.111, 0.121],
        [0.102, 0.112, 0.122],
        [0.103, 0.113, 0.123],
        [0.104, 0.114, 0.124]]])

In [13]:
test3d = np.array(
    [[[1 , 2 , 3 , 4 ],
      [5 , 6 , 7 , 8 ],
      [9 , 10, 11, 12]],
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]]
)
test3d.shape

(2, 3, 4)

In [15]:
test3d.transpose(0, 2, 1)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])